---
name: CI
'on':
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * 1"

jobs:

  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Install check dependencies.
        run: sudo apt-get install -y shellcheck

      - name: Install and run pre-commits.
        run: |
          make pre-commit

  test:
    name: Test
    #needs: check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        container:
          - 'debian_stable'
          - 'debian_testing'
          - 'fedora_latest'
          - 'fedora_rawhide'
          - 'ubuntu_2204'
      fail-fast: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker build -t ${{ matrix.container }} -f tests/dockerfiles/Dockerfile_${{ matrix.container
          }} .

      - name: Run tests in containers.
        run: docker run --rm -v $(pwd):/git-peak-extended ${{ matrix.container }} sh -c "bash
          /git-peak-extended/tests/run_tests.sh"
