---
name: CI
'on':
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * 1"

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5

      - name: Install check dependencies.
        run: sudo apt-get install -y shellcheck

      - name: Install and run pre-commits.
        run: |
          # temporarily forcefully upgrade+install pre-commit package to get newer
          # version than is pre-installed in Ubuntu 22.04 runner image
          sudo pip install --upgrade --break-system-packages pre-commit
          make pre-commit

  test:
    name: Test
    #needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - 'debian_stable'
          - 'debian_testing'
          - 'fedora_latest'
          - 'fedora_rawhide'
          - 'ubuntu_2204'
          - 'ubuntu_2404'
      fail-fast: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5

      - name: Build Docker images
        run: docker build -t ${{ matrix.container }} -f tests/dockerfiles/Dockerfile_${{ matrix.container
          }} .

      - name: Run tests in containers.
        run: docker run --rm -v $(pwd):/git-peak-extended ${{ matrix.container }} sh -c "bash
          /git-peak-extended/tests/run_tests.sh"

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
